CREATE TABLE IF NOT EXISTS hisab."contacts" (
  "id" SERIAL PRIMARY KEY,
  "companyId" INTEGER NOT NULL REFERENCES hisab."companies"(id) ON DELETE CASCADE,
  "gstin" TEXT,
  "name" TEXT NOT NULL,
  "mobile" TEXT,
  "email" TEXT,
  "dueDays" INTEGER,
  "currency" TEXT DEFAULT 'INR',
  "billingAddress1" TEXT,
  "billingAddress2" TEXT,
  "billingCity" TEXT,
  "billingPincode" TEXT,
  "billingState" TEXT,
  "billingCountry" TEXT DEFAULT 'India',
  "shippingAddress1" TEXT,
  "shippingAddress2" TEXT,
  "shippingCity" TEXT,
  "shippingPincode" TEXT,
  "shippingState" TEXT,
  "shippingCountry" TEXT DEFAULT 'India',
  "isShippingSame" BOOLEAN DEFAULT FALSE,
  "openingBalance" DECIMAL(15, 2) DEFAULT 0.00,
  "remainingBalance" DECIMAL(15, 2) DEFAULT 0.00,
  "balanceType" TEXT CHECK ("balanceType" IN ('payable', 'receivable')) DEFAULT 'payable',
  "enablePortal" BOOLEAN DEFAULT FALSE,
  "notes" TEXT,
  "createdBy" INTEGER REFERENCES hisab."users"(id) ON DELETE SET NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);