
CREATE TABLE hisab.purchases (
	id serial4 NOT NULL,
	"companyId" int4 NOT NULL,
	"userId" int4 NOT NULL,
	"bankAccountId" int4 NULL,
	"contactId" int4 NULL,
	"invoiceNumber" text NOT NULL,
	"invoiceDate" date NOT NULL,
	"taxType" text NULL,
	"discountValueType" text DEFAULT 'percentage'::text NULL,
	"discountValue" numeric(10, 2) DEFAULT 0 NULL,
	"roundOff" numeric(10, 2) DEFAULT 0 NULL,
	"internalNotes" text NULL,
	"basicAmount" numeric(15, 2) DEFAULT 0 NULL,
	"totalDiscount" numeric(15, 2) DEFAULT 0 NULL,
	"taxAmount" numeric(15, 2) DEFAULT 0 NULL,
	"netPayable" numeric(15, 2) DEFAULT 0 NULL,
	"createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	"updatedAt" timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	"deletedAt" timestamp NULL,
	status text DEFAULT 'pending'::text NULL,
	remaining_amount numeric(15, 2) DEFAULT 0.00 NULL,
	paid_amount numeric(15, 2) DEFAULT 0.00 NULL,
	"deletedBy" int4 NULL,
	"pdfUrl" text NULL,
	"rateType" varchar(50) DEFAULT 'without_tax'::character varying NULL,
	"transportationCharge" numeric(15, 2) NULL,
	"discountScope" text NULL,
	CONSTRAINT purchases_check CHECK (((("bankAccountId" IS NOT NULL) AND ("contactId" IS NULL)) OR (("bankAccountId" IS NULL) AND ("contactId" IS NOT NULL)) OR (("bankAccountId" IS NOT NULL) AND ("contactId" IS NOT NULL)))),
	CONSTRAINT purchases_pkey PRIMARY KEY (id),
	CONSTRAINT "purchases_rateType_check" CHECK ((("rateType")::text = ANY ((ARRAY['with_tax'::character varying, 'without_tax'::character varying])::text[]))),
	CONSTRAINT purchases_status_check CHECK ((status = ANY (ARRAY['paid'::text, 'pending'::text])))
);
