CREATE TABLE hisab.sales (
	id serial4 NOT NULL,
	"companyId" int4 NOT NULL,
	"userId" int4 NOT NULL,
	"bankAccountId" int4 NULL,
	"contactId" int4 NULL,
	"invoiceNumber" text NOT NULL,
	"invoiceDate" date NOT NULL,
	"taxType" text NULL,
	"rateType" varchar(50) DEFAULT 'without_tax'::character varying NULL,
	"discountScope" text DEFAULT 'per_item_and_invoice'::text NULL,
	"discountValueType" text DEFAULT 'percentage'::text NULL,
	"discountValue" numeric(10, 2) DEFAULT 0 NULL,
	"basicAmount" numeric(15, 2) DEFAULT 0 NULL,
	"totalItemDiscount" numeric(15, 2) DEFAULT 0 NULL,
	"invoiceDiscount" numeric(15, 2) DEFAULT 0 NULL,
	"totalDiscount" numeric(15, 2) DEFAULT 0 NULL,
	"taxAmount" numeric(15, 2) DEFAULT 0 NULL,
	"transportationCharge" numeric(15, 2) DEFAULT 0 NULL,
	"roundOff" numeric(10, 2) DEFAULT 0 NULL,
	"netReceivable" numeric(15, 2) DEFAULT 0 NULL,
	status text DEFAULT 'pending'::text NULL,
	remaining_amount numeric(15, 2) DEFAULT 0.00 NULL,
	paid_amount numeric(15, 2) DEFAULT 0.00 NULL,
	"internalNotes" text NULL,
	"createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	"updatedAt" timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	"deletedAt" timestamp NULL,
	"deletedBy" int4 NULL,
	CONSTRAINT sales_pkey PRIMARY KEY (id),
	CONSTRAINT sales_status_check CHECK ((status = ANY (ARRAY['paid'::text, 'pending'::text])))
);
